/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hogwarts;

/**
 *
 * @authors Gabriel Björk & Murhaf Jammal
 */
public class AdministratorMeny extends javax.swing.JFrame {

    private int id;

    /**
     * Creates new form AdministratorMeny
     */
    public AdministratorMeny(int id) {
        initComponents();
        this.id = id;
        this.setLocationRelativeTo(null); // Gör att JFramen dyker upp i mitten av skärmen
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnStang = new javax.swing.JButton();
        lblRubrik = new javax.swing.JLabel();
        btnRegistreraNyElev = new javax.swing.JButton();
        btnAndraElevInfo = new javax.swing.JButton();
        btnTaBortElever = new javax.swing.JButton();
        btnRegistreraLarare = new javax.swing.JButton();
        btnGeAdmin = new javax.swing.JButton();
        btnAndraLararInfo = new javax.swing.JButton();
        btnTaBortLarare = new javax.swing.JButton();
        btnHusPoang = new javax.swing.JButton();
        btnNyKurs = new javax.swing.JButton();
        btnAndraKursInfo = new javax.swing.JButton();
        btnTaBortKurs = new javax.swing.JButton();
        btnAndraElevhemsPrefekt = new javax.swing.JButton();
        btnAndraElevhemsForestandare = new javax.swing.JButton();
        lblElevarenden = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblLarararenden = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        lblKursarenden = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        lblElevhemsarenden = new javax.swing.JLabel();
        btnAndraLosenord = new javax.swing.JButton();
        BtnRegistreraBetyg = new javax.swing.JButton();
        btnAndrabetyg = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnStang.setText("Logga ut");
        btnStang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStangActionPerformed(evt);
            }
        });

        lblRubrik.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblRubrik.setText("Vad vill du göra idag?");

        btnRegistreraNyElev.setText("Registrera nya elever");
        btnRegistreraNyElev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistreraNyElevActionPerformed(evt);
            }
        });

        btnAndraElevInfo.setText("Ändra information på existerande elever");
        btnAndraElevInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAndraElevInfoActionPerformed(evt);
            }
        });

        btnTaBortElever.setText("Ta bort elever ur systemet");
        btnTaBortElever.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaBortEleverActionPerformed(evt);
            }
        });

        btnRegistreraLarare.setText("Registrera nya lärare");
        btnRegistreraLarare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistreraLarareActionPerformed(evt);
            }
        });

        btnGeAdmin.setText("Ge administratörstatus till existerande lärare");
        btnGeAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGeAdminActionPerformed(evt);
            }
        });

        btnAndraLararInfo.setText("Ändra information på existerande lärare");
        btnAndraLararInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAndraLararInfoActionPerformed(evt);
            }
        });

        btnTaBortLarare.setText("Ta bort lärare ur systemet");
        btnTaBortLarare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaBortLarareActionPerformed(evt);
            }
        });

        btnHusPoang.setText("Lägg till / Ta bort  elevhemspoäng");
        btnHusPoang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHusPoangActionPerformed(evt);
            }
        });

        btnNyKurs.setText("Registrera nya kurser");
        btnNyKurs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNyKursActionPerformed(evt);
            }
        });

        btnAndraKursInfo.setText("Ändra information på existerande kurser");
        btnAndraKursInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAndraKursInfoActionPerformed(evt);
            }
        });

        btnTaBortKurs.setText("Ta bort existerande kurser");
        btnTaBortKurs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaBortKursActionPerformed(evt);
            }
        });

        btnAndraElevhemsPrefekt.setText("Ändra prefekt för elevhem");
        btnAndraElevhemsPrefekt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAndraElevhemsPrefektActionPerformed(evt);
            }
        });

        btnAndraElevhemsForestandare.setText("Ändra elevhemsföreståndare för elevhem");
        btnAndraElevhemsForestandare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAndraElevhemsForestandareActionPerformed(evt);
            }
        });

        lblElevarenden.setText("Elevärenden:");

        lblLarararenden.setText("Lärarärenden:");

        lblKursarenden.setText("Kursärenden:");

        lblElevhemsarenden.setText("Elevhemsärenden:");

        btnAndraLosenord.setText("Ändra eget lösenord");
        btnAndraLosenord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAndraLosenordActionPerformed(evt);
            }
        });

        BtnRegistreraBetyg.setText("Registrera kursbetyg för elever");
        BtnRegistreraBetyg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegistreraBetygActionPerformed(evt);
            }
        });

        btnAndrabetyg.setText("Ändra kursbetyg för elever");
        btnAndrabetyg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAndrabetygActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(jSeparator2)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jSeparator3)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnRegistreraLarare, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAndraLararInfo)
                        .addGap(41, 41, 41)
                        .addComponent(btnGeAdmin)
                        .addGap(23, 23, 23))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAndraKursInfo)
                        .addGap(84, 84, 84)
                        .addComponent(btnNyKurs)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnTaBortKurs)
                        .addGap(38, 38, 38))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblElevarenden)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnRegistreraNyElev)
                                .addGap(39, 39, 39)
                                .addComponent(btnAndraElevInfo)
                                .addGap(78, 78, 78)
                                .addComponent(btnTaBortElever))
                            .addComponent(lblElevhemsarenden)
                            .addComponent(lblRubrik)
                            .addComponent(lblKursarenden)
                            .addComponent(lblLarararenden)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(138, 138, 138)
                                .addComponent(btnTaBortLarare)
                                .addGap(114, 114, 114)
                                .addComponent(btnAndraLosenord)))
                        .addGap(113, 116, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnStang, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(btnAndraElevhemsPrefekt)
                .addGap(29, 29, 29)
                .addComponent(btnAndraElevhemsForestandare)
                .addGap(46, 46, 46)
                .addComponent(btnHusPoang)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(BtnRegistreraBetyg)
                .addGap(136, 136, 136)
                .addComponent(btnAndrabetyg)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblRubrik)
                .addGap(9, 9, 9)
                .addComponent(lblElevarenden)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistreraNyElev)
                    .addComponent(btnAndraElevInfo)
                    .addComponent(btnTaBortElever))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnRegistreraBetyg)
                    .addComponent(btnAndrabetyg))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblLarararenden)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistreraLarare)
                    .addComponent(btnAndraLararInfo)
                    .addComponent(btnGeAdmin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTaBortLarare)
                    .addComponent(btnAndraLosenord))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblKursarenden, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAndraKursInfo)
                            .addComponent(btnNyKurs)
                            .addComponent(btnTaBortKurs))
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblElevhemsarenden)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAndraElevhemsPrefekt)
                            .addComponent(btnAndraElevhemsForestandare)
                            .addComponent(btnHusPoang))
                        .addGap(21, 21, 21)))
                .addComponent(btnStang)
                .addGap(6, 6, 6))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Stänger ner befentlig JFrame
    private void btnStangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStangActionPerformed
        //Stänger ner befentlig JFrame
        this.dispose();
    }//GEN-LAST:event_btnStangActionPerformed


    private void btnAndraElevInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAndraElevInfoActionPerformed
        new AndraInformationPaEnElev().setVisible(true); //Skapar och startar en ny AndraInformationPaEnElev
    }//GEN-LAST:event_btnAndraElevInfoActionPerformed


    private void btnRegistreraNyElevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistreraNyElevActionPerformed
        new RegistreraNyElev().setVisible(true);  //Skapar och startar en ny RegistreraNyElev
    }//GEN-LAST:event_btnRegistreraNyElevActionPerformed


    private void btnTaBortEleverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaBortEleverActionPerformed
        new TaBortElev().setVisible(true); //Skapar och startar en ny TaBortElev
    }//GEN-LAST:event_btnTaBortEleverActionPerformed


    private void btnRegistreraLarareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistreraLarareActionPerformed
        new RegistreraNyLarare().setVisible(true); //Skapar och startar en ny RegistreraNyLarare
    }//GEN-LAST:event_btnRegistreraLarareActionPerformed


    private void btnAndraLararInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAndraLararInfoActionPerformed
        new AndraInformationPaEnLarare().setVisible(true); //Skapar och startar en ny AndraInformationPaEnLarare
    }//GEN-LAST:event_btnAndraLararInfoActionPerformed


    private void btnGeAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGeAdminActionPerformed
        new GeAdminstatus().setVisible(true); //Skapar och startar en ny GeAdminstatus
    }//GEN-LAST:event_btnGeAdminActionPerformed


    private void btnTaBortLarareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaBortLarareActionPerformed
        new TaBortLarare().setVisible(true);  //Skapar och startar en ny TaBortLarare
    }//GEN-LAST:event_btnTaBortLarareActionPerformed


    private void btnAndraKursInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAndraKursInfoActionPerformed
        new AndraInformationPaEnKurs().setVisible(true);  //Skapar och startar en ny AndraInformationPaEnKurs
    }//GEN-LAST:event_btnAndraKursInfoActionPerformed


    private void btnNyKursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNyKursActionPerformed
        new RegistreraNyKurs().setVisible(true); //Skapar och startar en ny RegistreraNyKurs
    }//GEN-LAST:event_btnNyKursActionPerformed


    private void btnTaBortKursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaBortKursActionPerformed
        new TaBortKurs().setVisible(true); //Skapar och startar en ny TaBortKurs
    }//GEN-LAST:event_btnTaBortKursActionPerformed


    private void btnAndraElevhemsPrefektActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAndraElevhemsPrefektActionPerformed
        new AndraPrefekt().setVisible(true); //Skapar och startar en ny AndraPrefekt
    }//GEN-LAST:event_btnAndraElevhemsPrefektActionPerformed


    private void btnAndraElevhemsForestandareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAndraElevhemsForestandareActionPerformed
        new AndraElevhemsForestandare().setVisible(true); //Skapar och startar en ny AndraElevhemsForestandare
    }//GEN-LAST:event_btnAndraElevhemsForestandareActionPerformed


    private void btnHusPoangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHusPoangActionPerformed
        new AndraHuspoang().setVisible(true); //Skapar och startar en ny AndraHuspoang
    }//GEN-LAST:event_btnHusPoangActionPerformed

    private void btnAndraLosenordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAndraLosenordActionPerformed
        new BytLosenord(id).setVisible(true);
    }//GEN-LAST:event_btnAndraLosenordActionPerformed

    private void BtnRegistreraBetygActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegistreraBetygActionPerformed
        new RegistreraKursbetygForEnElev().setVisible(true);
    }//GEN-LAST:event_BtnRegistreraBetygActionPerformed

    private void btnAndrabetygActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAndrabetygActionPerformed
        new AndraKursbetygForEnElev().setVisible(true);
    }//GEN-LAST:event_btnAndrabetygActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnRegistreraBetyg;
    private javax.swing.JButton btnAndraElevInfo;
    private javax.swing.JButton btnAndraElevhemsForestandare;
    private javax.swing.JButton btnAndraElevhemsPrefekt;
    private javax.swing.JButton btnAndraKursInfo;
    private javax.swing.JButton btnAndraLararInfo;
    private javax.swing.JButton btnAndraLosenord;
    private javax.swing.JButton btnAndrabetyg;
    private javax.swing.JButton btnGeAdmin;
    private javax.swing.JButton btnHusPoang;
    private javax.swing.JButton btnNyKurs;
    private javax.swing.JButton btnRegistreraLarare;
    private javax.swing.JButton btnRegistreraNyElev;
    private javax.swing.JButton btnStang;
    private javax.swing.JButton btnTaBortElever;
    private javax.swing.JButton btnTaBortKurs;
    private javax.swing.JButton btnTaBortLarare;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lblElevarenden;
    private javax.swing.JLabel lblElevhemsarenden;
    private javax.swing.JLabel lblKursarenden;
    private javax.swing.JLabel lblLarararenden;
    private javax.swing.JLabel lblRubrik;
    // End of variables declaration//GEN-END:variables
}
