/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hogwarts;

import javax.swing.JOptionPane;
import oru.inf.InfDB;

/**
 *
 * @author @authors Gabriel Björk & Murhaf Jammal
 */
public class AndraInformationPaEnElev extends javax.swing.JFrame {
    
    private DataHanterare dataHanterare;
    private InfDB databasen;
    private int id;

    /**
     * Creates new form AndraInformationOmEnElev
     */
    public AndraInformationPaEnElev() {
        databasen = DataHanterare.dataHanterare();
        dataHanterare = new DataHanterare();
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblRubrik = new javax.swing.JLabel();
        lblElevensFornamn = new javax.swing.JLabel();
        lblElevensEfternamn = new javax.swing.JLabel();
        btnSokElev = new javax.swing.JButton();
        lblDenGamlaInfo = new javax.swing.JLabel();
        lblStatusGamla = new javax.swing.JLabel();
        lblStatusGamlaSvar = new javax.swing.JLabel();
        tfElevensFornamn = new javax.swing.JTextField();
        tfElevensEfternamn = new javax.swing.JTextField();
        lblDenNyaInfo = new javax.swing.JLabel();
        tfNyttFornamn = new javax.swing.JTextField();
        tfNyttEfternamn = new javax.swing.JTextField();
        lblNyttFornamn = new javax.swing.JLabel();
        lblNyttEfternamn = new javax.swing.JLabel();
        lblNyttSovsal = new javax.swing.JLabel();
        lblStatusNya = new javax.swing.JLabel();
        lblStatusNyaSvar = new javax.swing.JLabel();
        btnAndraInfo = new javax.swing.JButton();
        btnStang = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cmbElevhem = new javax.swing.JComboBox<>();
        lblVaning = new javax.swing.JLabel();
        cmbVaning = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        lblRubrik.setFont(new java.awt.Font("Dialog", 0, 22)); // NOI18N
        lblRubrik.setText("Ändra information på en elev");

        lblElevensFornamn.setText("Förnamn:");

        lblElevensEfternamn.setText("Efternamn:");

        btnSokElev.setText("Sök Elev");
        btnSokElev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSokElevActionPerformed(evt);
            }
        });

        lblDenGamlaInfo.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblDenGamlaInfo.setText("1. Ange namnet på eleven");

        lblStatusGamla.setText("Status:");

        lblDenNyaInfo.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblDenNyaInfo.setText("2. Fyll in den nya informationen");

        lblNyttFornamn.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblNyttFornamn.setText("Nytt Förnamn:");

        lblNyttEfternamn.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblNyttEfternamn.setText("Nytt Efternamn:");

        lblNyttSovsal.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblNyttSovsal.setText("Ny Sovsal:");

        lblStatusNya.setText("Status:");

        btnAndraInfo.setText("Ändra Informationen");
        btnAndraInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAndraInfoActionPerformed(evt);
            }
        });

        btnStang.setText("Stäng");
        btnStang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStangActionPerformed(evt);
            }
        });

        jLabel1.setText("Elevhem:");

        lblVaning.setText("Våning:");

        cmbVaning.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDenNyaInfo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblElevensEfternamn)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnSokElev)
                                        .addGap(31, 31, 31))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblElevensFornamn)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(tfElevensEfternamn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                                                .addComponent(tfElevensFornamn, javax.swing.GroupLayout.Alignment.LEADING))
                                            .addComponent(lblDenGamlaInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)))
                                .addComponent(lblStatusGamla))
                            .addComponent(lblRubrik, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblStatusGamlaSvar, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(84, 84, 84)
                                        .addComponent(lblStatusNya)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblStatusNyaSvar, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblNyttSovsal)
                                            .addComponent(cmbElevhem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(212, 212, 212)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblVaning)
                                            .addComponent(cmbVaning, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnAndraInfo)
                                .addGap(128, 128, 128)))
                        .addComponent(btnStang)
                        .addGap(20, 20, 20))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tfNyttFornamn, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tfNyttEfternamn, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(101, 101, 101))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNyttFornamn, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblNyttEfternamn)
                        .addGap(122, 122, 122))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblRubrik)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDenGamlaInfo)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(lblElevensFornamn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfElevensFornamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(lblElevensEfternamn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tfElevensEfternamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblStatusGamlaSvar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnSokElev)
                                .addComponent(lblStatusGamla)))
                        .addGap(51, 51, 51)))
                .addComponent(lblDenNyaInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNyttFornamn)
                            .addComponent(lblNyttEfternamn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfNyttEfternamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfNyttFornamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblNyttSovsal, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(lblVaning))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbElevhem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbVaning, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnAndraInfo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblStatusNya)
                            .addComponent(lblStatusNyaSvar, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnStang)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSokElevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSokElevActionPerformed
        lblStatusNyaSvar.setText("");
        if (Validering.FaltArTom(tfElevensFornamn) || Validering.FaltArTom(tfElevensEfternamn)) {
            lblStatusGamlaSvar.setText("Hittades Ej!");
        } else {
            String fornamn = tfElevensFornamn.getText();
            String elevnsFornamn = dataHanterare.namnFormat(fornamn);
            String efternamn = tfElevensEfternamn.getText();
            String elevensEfternamn = dataHanterare.efternamnFormat(efternamn);
            int elevId = dataHanterare.getElevId(elevnsFornamn, elevensEfternamn);
            if (elevId != 0) {
                lblStatusGamlaSvar.setText("Hittad!");
                id = elevId;
                tfNyttFornamn.setText(dataHanterare.getElevFornamn(elevId));
                tfNyttEfternamn.setText(dataHanterare.getElevEfternamn(elevId));
                cmbElevhem.setSelectedItem(dataHanterare.getElevhemForElev(elevId));
                cmbVaning.setSelectedIndex(dataHanterare.getSovsalVaning(elevId, dataHanterare.getElevhemId(cmbElevhem)) - 1);
                tfElevensFornamn.setText(null);
                tfElevensEfternamn.setText(null);
            } else {
                lblStatusGamlaSvar.setText("Hittades Ej!");
            }
        }
    }//GEN-LAST:event_btnSokElevActionPerformed

    private void btnAndraInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAndraInfoActionPerformed
        if (lblStatusGamlaSvar.getText().equals("Hittad!")) {
            lblStatusGamlaSvar.setText("");
            if (!Validering.FaltArTom(tfNyttEfternamn) && !Validering.FaltArTom(tfNyttFornamn)) {
                
                String nyaFornamn = tfNyttFornamn.getText();
                String elevensNyaFornamn = dataHanterare.namnFormat(nyaFornamn);
                String nyaEfternamn = tfNyttEfternamn.getText();
                String elevensNyaEfternamn = dataHanterare.efternamnFormat(nyaEfternamn);
                int elevhemId = dataHanterare.getElevhemId(cmbElevhem);
                int sovsalId = dataHanterare.getSovsalId(elevhemId, cmbVaning);
                int elevId = id;
                
                dataHanterare.AndraElevInformation(elevensNyaFornamn, elevensNyaEfternamn, sovsalId, elevId);
                lblStatusNyaSvar.setText("Ändringen Lyckades!");
            } else {
                lblStatusNyaSvar.setText("Ändringen Lyckades Ej efter if faltArTom!");
            }
            
        } else {
            JOptionPane.showMessageDialog(null, "Du måste först hitta eleven för att kunna ändra sin information");
            lblStatusNyaSvar.setText("Ändringen Lyckades Ej efter hittad!");
        }
        

    }//GEN-LAST:event_btnAndraInfoActionPerformed

    private void btnStangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStangActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnStangActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        if (cmbElevhem.getItemCount() == 0) {
            dataHanterare.laggTillElevhem(cmbElevhem);
        }
    }//GEN-LAST:event_formWindowActivated


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAndraInfo;
    private javax.swing.JButton btnSokElev;
    private javax.swing.JButton btnStang;
    private javax.swing.JComboBox<String> cmbElevhem;
    private javax.swing.JComboBox<String> cmbVaning;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblDenGamlaInfo;
    private javax.swing.JLabel lblDenNyaInfo;
    private javax.swing.JLabel lblElevensEfternamn;
    private javax.swing.JLabel lblElevensFornamn;
    private javax.swing.JLabel lblNyttEfternamn;
    private javax.swing.JLabel lblNyttFornamn;
    private javax.swing.JLabel lblNyttSovsal;
    private javax.swing.JLabel lblRubrik;
    private javax.swing.JLabel lblStatusGamla;
    private javax.swing.JLabel lblStatusGamlaSvar;
    private javax.swing.JLabel lblStatusNya;
    private javax.swing.JLabel lblStatusNyaSvar;
    private javax.swing.JLabel lblVaning;
    private javax.swing.JTextField tfElevensEfternamn;
    private javax.swing.JTextField tfElevensFornamn;
    private javax.swing.JTextField tfNyttEfternamn;
    private javax.swing.JTextField tfNyttFornamn;
    // End of variables declaration//GEN-END:variables
}
