/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hogwarts;

import oru.inf.InfDB;

/**
 *
 * @authors Gabriel Björk & Murhaf Jammal
 */
public class AndraHuspoang extends javax.swing.JFrame {

    private DataHanterare dataHanterare;
    private InfDB databasen;
    //new AndraHuspoang().setVisible(true);

    /**
     * Creates new form Huspoang
     */
    public AndraHuspoang() {
        databasen = DataHanterare.dataHanterare();
        dataHanterare = new DataHanterare();
        initComponents();
        this.setLocationRelativeTo(null); // Gör att JFramen dyker upp i mitten av skärmen
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitel = new javax.swing.JLabel();
        lblElevhem = new javax.swing.JLabel();
        cboxElevhem = new javax.swing.JComboBox<>();
        txtPoang = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        lblPoang = new javax.swing.JLabel();
        lblAdd = new javax.swing.JLabel();
        lblRemove = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        lblTitel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTitel.setText("Lägg till / dra av huspoäng");

        lblElevhem.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblElevhem.setText("Välj elevhem:");

        cboxElevhem.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtPoang.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        btnAdd.setText("Lägg till");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnRemove.setText("Dra av");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });

        btnClose.setText("Stäng");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        lblPoang.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblPoang.setText("Poäng:");

        lblAdd.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N

        lblRemove.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAdd)
                    .addComponent(btnRemove)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(lblAdd, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblRemove, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblTitel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(lblElevhem)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(cboxElevhem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(lblPoang)
                            .addGap(18, 18, 18)
                            .addComponent(txtPoang, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(48, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnClose)
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblTitel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblElevhem)
                    .addComponent(cboxElevhem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPoang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPoang))
                .addGap(18, 18, 18)
                .addComponent(btnAdd)
                .addGap(10, 10, 10)
                .addComponent(lblAdd)
                .addGap(18, 18, 18)
                .addComponent(btnRemove)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(lblRemove)
                .addGap(18, 18, 18)
                .addComponent(btnClose)
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        //Stänger ner befentlig JFrame
        this.dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        if (cboxElevhem.getItemCount() == 0) {
            dataHanterare.laggTillElevhem(cboxElevhem); //Hämtar elevhemsnamn från databasen och lägger in dem i elevhems combobox
        }
    }//GEN-LAST:event_formWindowActivated

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        lblAdd.setText(""); //raderar texten i status label
        lblRemove.setText(""); //raderar texten i status label
        if (!Validering.FaltArTom(txtPoang)) { //Validerar att fält inte är tomt
            if (Validering.arHeltal(txtPoang)) { // Validerar att angivna poäng är heltal
                if (dataHanterare.laggTillHuspoang(cboxElevhem, txtPoang)) { //Metodanrop som lägger till huspoäng
                    lblAdd.setText(cboxElevhem.getSelectedItem() + " har blivit tilldelad " + txtPoang.getText() + " poäng"); //Visar text om ändringen lyckades
                }
            }
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        lblRemove.setText(""); //raderar texten i status label
        lblAdd.setText(""); //raderar texten i status label
        if (!Validering.FaltArTom(txtPoang)) { //Validerar att fält inte är tomt
            if (Validering.arHeltal(txtPoang)) { // Validerar att angivna poäng är heltal
                String poangString = txtPoang.getText(); //Hämtar angivna poäng
                int poangInt = Integer.parseInt(poangString); //Gör hämtade poäng till integer
                String elevhemsNamn = cboxElevhem.getSelectedItem().toString(); //Hämtar valt elevhemsnamn
                int elevhemmetsPoang = dataHanterare.kollaHuspoang(elevhemsNamn); //Hämtar poäng som valt elevhem har
                if (dataHanterare.huspoangRacker(elevhemmetsPoang, poangInt)) {  //kollar om elevhemmet har tillräckligt med poäng

                    if (dataHanterare.taBortHuspoang(cboxElevhem, txtPoang)) { //Metodanrop som tar bort huspoäng 
                        lblRemove.setText(cboxElevhem.getSelectedItem() + " har blivit fråntagen " + txtPoang.getText() + " poäng"); //visar text
                    }
                }
            }
        }
    }//GEN-LAST:event_btnRemoveActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnRemove;
    private javax.swing.JComboBox<String> cboxElevhem;
    private javax.swing.JLabel lblAdd;
    private javax.swing.JLabel lblElevhem;
    private javax.swing.JLabel lblPoang;
    private javax.swing.JLabel lblRemove;
    private javax.swing.JLabel lblTitel;
    private javax.swing.JTextField txtPoang;
    // End of variables declaration//GEN-END:variables
}
