/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hogwarts;

import javax.swing.JOptionPane;
import oru.inf.InfDB;

/**
 *
 * @author @authors Gabriel Björk & Murhaf Jammal
 */
public class AndraInformationPaEnLarare extends javax.swing.JFrame {

    private DataHanterare dataHanterare;
    private InfDB databasen;

    /**
     * Creates new form AndraInformationPaEnLarare
     */
    public AndraInformationPaEnLarare() {
        initComponents();
        databasen = DataHanterare.dataHanterare();
        dataHanterare = new DataHanterare();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblDenGamlaInfo = new javax.swing.JLabel();
        lblLararensFornamn = new javax.swing.JLabel();
        lblLararensEfternamn = new javax.swing.JLabel();
        tfLararensFornamn = new javax.swing.JTextField();
        tfLararensEfternamn = new javax.swing.JTextField();
        btnSokLarare = new javax.swing.JButton();
        lblStatusGamla = new javax.swing.JLabel();
        lblStatusGamlaSvar = new javax.swing.JLabel();
        lblDenNyaInfo = new javax.swing.JLabel();
        lblNyttFornamn = new javax.swing.JLabel();
        tfNyttFornamn = new javax.swing.JTextField();
        lblNyttEfternamn = new javax.swing.JLabel();
        tfNyttEfternamn = new javax.swing.JTextField();
        btnAndraInfo = new javax.swing.JButton();
        lblStatusNya = new javax.swing.JLabel();
        lblStatusNyaSvar = new javax.swing.JLabel();
        btnStang = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel1.setText("Ändra information på en lärare");

        lblDenGamlaInfo.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblDenGamlaInfo.setText("1. Ange namnet på lararen");

        lblLararensFornamn.setText("Förnamn:");

        lblLararensEfternamn.setText("Efternamn:");

        btnSokLarare.setText("Sök Lärare");
        btnSokLarare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSokLarareActionPerformed(evt);
            }
        });

        lblStatusGamla.setText("Status:");

        lblDenNyaInfo.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblDenNyaInfo.setText("2. Fyll in den nya informationen");

        lblNyttFornamn.setText("Nytt Förnamn:");

        lblNyttEfternamn.setText("Nytt Efternamn:");

        btnAndraInfo.setText("Ändra Informationen");
        btnAndraInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAndraInfoActionPerformed(evt);
            }
        });

        lblStatusNya.setText("Status:");

        btnStang.setText("Stäng");
        btnStang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStangActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDenGamlaInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(btnAndraInfo))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblLararensFornamn)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tfLararensFornamn, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(37, 37, 37)
                                    .addComponent(lblLararensEfternamn))
                                .addComponent(btnSokLarare))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tfLararensEfternamn, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(107, 107, 107)
                            .addComponent(lblStatusGamla)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblStatusGamlaSvar, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(127, 127, 127))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblDenNyaInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(257, 257, 257))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnStang))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblNyttFornamn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(334, 334, 334)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tfNyttFornamn, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblNyttEfternamn)
                        .addGap(18, 18, 18)
                        .addComponent(tfNyttEfternamn, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblStatusNya)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblStatusNyaSvar, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDenGamlaInfo)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfLararensFornamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLararensFornamn)
                    .addComponent(lblLararensEfternamn)
                    .addComponent(tfLararensEfternamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSokLarare)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblStatusGamla)
                    .addComponent(lblStatusGamlaSvar, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addComponent(lblDenNyaInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNyttFornamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNyttFornamn)
                    .addComponent(lblNyttEfternamn)
                    .addComponent(tfNyttEfternamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnAndraInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblStatusNya)
                    .addComponent(lblStatusNyaSvar, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnStang)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSokLarareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSokLarareActionPerformed
        lblStatusNyaSvar.setText(null);
        if (Validering.FaltArTom(tfLararensFornamn) || Validering.FaltArTom(tfLararensEfternamn)) {
            lblStatusGamlaSvar.setText("Hittades Ej!");
        } else {
            String lararensFornamn = dataHanterare.namnFormat(tfLararensFornamn.getText());
            String lararensEfternamn = dataHanterare.efternamnFormat(tfLararensEfternamn.getText());
            int lararId = dataHanterare.getLararID(lararensFornamn, lararensEfternamn);
            if (lararId != 0) {
                lblStatusGamlaSvar.setText("Hittad!");
            } else {
                lblStatusGamlaSvar.setText("Hittades Ej!");
            }
        }
    }//GEN-LAST:event_btnSokLarareActionPerformed

    private void btnAndraInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAndraInfoActionPerformed
        if (lblStatusGamlaSvar.getText().equals("Hittad!")) {
            if (Validering.FaltArTom(tfNyttEfternamn) || Validering.FaltArTom(tfNyttFornamn)) {
                lblStatusNyaSvar.setText("Ändringen Lyckades Ej!");

            } else {

                String gamlaFornamn = tfLararensFornamn.getText();
                String lararensGamlaFornamn = dataHanterare.namnFormat(gamlaFornamn);
                String gamlaEfternamn = tfLararensEfternamn.getText();
                String lararensGamlaEfternamn = dataHanterare.efternamnFormat(gamlaEfternamn);
                String nyaFornamn = tfNyttFornamn.getText();
                String lararensNyaFornamn = dataHanterare.namnFormat(nyaFornamn);
                String nyaEfternamn = tfNyttEfternamn.getText();
                String lararensNyaEfternamn = dataHanterare.efternamnFormat(nyaEfternamn);

                dataHanterare.AndraLararInformation(lararensGamlaFornamn, lararensGamlaEfternamn, lararensNyaFornamn, lararensNyaEfternamn);
                lblStatusNyaSvar.setText("Ändringen Lyckades!");
            }

        } else {
            JOptionPane.showMessageDialog(null, "Du måste först hitta läraren för att kunna ändra sin information");
            lblStatusNyaSvar.setText("Ändringen Lyckades Ej!");
        }

    }//GEN-LAST:event_btnAndraInfoActionPerformed

    private void btnStangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStangActionPerformed

        this.dispose();
    }//GEN-LAST:event_btnStangActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAndraInfo;
    private javax.swing.JButton btnSokLarare;
    private javax.swing.JButton btnStang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblDenGamlaInfo;
    private javax.swing.JLabel lblDenNyaInfo;
    private javax.swing.JLabel lblLararensEfternamn;
    private javax.swing.JLabel lblLararensFornamn;
    private javax.swing.JLabel lblNyttEfternamn;
    private javax.swing.JLabel lblNyttFornamn;
    private javax.swing.JLabel lblStatusGamla;
    private javax.swing.JLabel lblStatusGamlaSvar;
    private javax.swing.JLabel lblStatusNya;
    private javax.swing.JLabel lblStatusNyaSvar;
    private javax.swing.JTextField tfLararensEfternamn;
    private javax.swing.JTextField tfLararensFornamn;
    private javax.swing.JTextField tfNyttEfternamn;
    private javax.swing.JTextField tfNyttFornamn;
    // End of variables declaration//GEN-END:variables
}
