/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hogwarts;

import javax.swing.JOptionPane;
import oru.inf.InfDB;

/**
 *
 * @author @authors Gabriel Björk & Murhaf Jammal
 */
public class AndraKursbetygForEnElev extends javax.swing.JFrame {

    private InfDB databasen;
    private DataHanterare dataHanterare;

    /**
     * Creates new form AndraKursbetygForEnElev
     */
    public AndraKursbetygForEnElev() {
        databasen = DataHanterare.dataHanterare();
        dataHanterare = new DataHanterare();
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblRubrikValjEnKursOchEttBetyg = new javax.swing.JLabel();
        cmbValjKurs = new javax.swing.JComboBox<>();
        lblKurs = new javax.swing.JLabel();
        tfElevensFornamn = new javax.swing.JTextField();
        lblElevensFornamn = new javax.swing.JLabel();
        lblElevensEfternamn = new javax.swing.JLabel();
        tfElevensEfternamn = new javax.swing.JTextField();
        lblDetNyaBetyget = new javax.swing.JLabel();
        cmbBetyg = new javax.swing.JComboBox<>();
        btnAndraBetyget = new javax.swing.JButton();
        btnStang = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        lblRubrikValjEnKursOchEttBetyg.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblRubrikValjEnKursOchEttBetyg.setText("Välj en kurs och ett betyg och ange elevnamn");

        lblKurs.setText("Kurs:");

        lblElevensFornamn.setText("Elevens Förnamn:");

        lblElevensEfternamn.setText("Elevens Efternamn:");

        lblDetNyaBetyget.setText("Det nya betyget:");

        btnAndraBetyget.setText("Ändra Betyget!");
        btnAndraBetyget.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAndraBetygetActionPerformed(evt);
            }
        });

        btnStang.setText("Stäng");
        btnStang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStangActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblRubrikValjEnKursOchEttBetyg, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblKurs)
                            .addComponent(cmbValjKurs, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDetNyaBetyget)
                            .addComponent(cmbBetyg, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblElevensFornamn, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tfElevensFornamn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblElevensEfternamn)
                    .addComponent(tfElevensEfternamn, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnAndraBetyget, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(219, 219, 219))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnStang)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblRubrikValjEnKursOchEttBetyg)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKurs)
                    .addComponent(lblElevensFornamn)
                    .addComponent(lblElevensEfternamn)
                    .addComponent(lblDetNyaBetyget))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbValjKurs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfElevensFornamn, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfElevensEfternamn, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbBetyg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(btnAndraBetyget, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnStang)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAndraBetygetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAndraBetygetActionPerformed

        if (Validering.FaltArTom(tfElevensFornamn) || Validering.FaltArTom(tfElevensEfternamn)) {
            System.out.println("Problem med FaltArTom valideringen");
        } else {
            String fornamn = tfElevensFornamn.getText();
            String elevensFornamn = dataHanterare.namnFormat(fornamn);
            String efternamn = tfElevensEfternamn.getText();
            String elevensEfternamn = dataHanterare.efternamnFormat(efternamn);
            int elevId = dataHanterare.getElevId(elevensFornamn, elevensEfternamn);
            String kursNamn = cmbValjKurs.getSelectedItem().toString();
            int kursId = dataHanterare.getKursId(kursNamn);
            String betyget = cmbBetyg.getSelectedItem().toString();

            if (elevId != 0) {

                if (dataHanterare.elevHarBetyg(elevId, kursId)) {
                    dataHanterare.andraKursbetygForEnElev(elevId, kursId, betyget);
                } else {
                    JOptionPane.showMessageDialog(null, "Eleven har inget betyg i den valda kursen. \n"
                            + "Använd knappen 'Registrera kursbetyg för elever' för att registrera ett nytt betyg istället.");
                }
            }

        }

    }//GEN-LAST:event_btnAndraBetygetActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated

        if (cmbValjKurs.getItemCount() == 0) {
            dataHanterare.laggTillKursnamn(cmbValjKurs);
        }
        if (cmbBetyg.getItemCount() == 0) {
            dataHanterare.laggTillBetygsBeteckning(cmbBetyg);
        }
    }//GEN-LAST:event_formWindowActivated

    private void btnStangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStangActionPerformed

        this.dispose();
    }//GEN-LAST:event_btnStangActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAndraBetyget;
    private javax.swing.JButton btnStang;
    private javax.swing.JComboBox<String> cmbBetyg;
    private javax.swing.JComboBox<String> cmbValjKurs;
    private javax.swing.JLabel lblDetNyaBetyget;
    private javax.swing.JLabel lblElevensEfternamn;
    private javax.swing.JLabel lblElevensFornamn;
    private javax.swing.JLabel lblKurs;
    private javax.swing.JLabel lblRubrikValjEnKursOchEttBetyg;
    private javax.swing.JTextField tfElevensEfternamn;
    private javax.swing.JTextField tfElevensFornamn;
    // End of variables declaration//GEN-END:variables
}
