/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hogwarts;

import oru.inf.InfDB;

/**
 *
 * @authors Gabriel Björk & Murhaf Jammal
 */
public class AndraInformationPaEnKurs extends javax.swing.JFrame {

    private InfDB databasen;
    private DataHanterare dataHanterare;

    /**
     * Creates new form AndraInformationPaEnKurs
     */
    public AndraInformationPaEnKurs() {
        databasen = DataHanterare.dataHanterare();
        dataHanterare = new DataHanterare();
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblRubrikValjKursen = new javax.swing.JLabel();
        lblRubrik = new javax.swing.JLabel();
        cmbKursnamn = new javax.swing.JComboBox<>();
        lblAngeDenNyaInfo = new javax.swing.JLabel();
        lblNyttKursnamn = new javax.swing.JLabel();
        tfNyttKursnamn = new javax.swing.JTextField();
        lblNyttStartdatum = new javax.swing.JLabel();
        NyttSlutdatum = new javax.swing.JLabel();
        lblNyKurslarare = new javax.swing.JLabel();
        lblNyttFornamn = new javax.swing.JLabel();
        lblNyttEfternamn = new javax.swing.JLabel();
        lblNyAmnesTillhorighet = new javax.swing.JLabel();
        lblArStartdatum = new javax.swing.JLabel();
        lblManadStartdatum = new javax.swing.JLabel();
        lblDagStartdatum = new javax.swing.JLabel();
        lblArSlutdatum = new javax.swing.JLabel();
        lblManadSlutdatum = new javax.swing.JLabel();
        lblDagSlutdatum = new javax.swing.JLabel();
        cmbAmnen = new javax.swing.JComboBox<>();
        tfArStartdatum = new javax.swing.JTextField();
        tfManadStartdatum = new javax.swing.JTextField();
        tfDagStartdatum = new javax.swing.JTextField();
        tfArSlutdatum = new javax.swing.JTextField();
        tfManadSlutdatum = new javax.swing.JTextField();
        tfDagSlutdatum = new javax.swing.JTextField();
        tfLararensFornamn = new javax.swing.JTextField();
        tfLararensEfternamn = new javax.swing.JTextField();
        btnUppdatera = new javax.swing.JButton();
        lblStatus = new javax.swing.JLabel();
        lblStatusSvar = new javax.swing.JLabel();
        btnStang = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        lblRubrikValjKursen.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblRubrikValjKursen.setText("Välj kursen som du vill uppdatera:");

        lblRubrik.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblRubrik.setText("Upddatera kursinformation");

        lblAngeDenNyaInfo.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblAngeDenNyaInfo.setText("Ange den nya informationen:");

        lblNyttKursnamn.setText("Nytt Kursnamn:");

        lblNyttStartdatum.setText("Nytt Startdatum:");

        NyttSlutdatum.setText("Nytt Slutdatum:");

        lblNyKurslarare.setText("Ny kurslärare:");

        lblNyttFornamn.setText("Förnamn:");

        lblNyttEfternamn.setText("Efternamn:");

        lblNyAmnesTillhorighet.setText("Ny ämnestillhörighet:");

        lblArStartdatum.setText("ÅÅÅÅ");

        lblManadStartdatum.setText("MM");

        lblDagStartdatum.setText("DD");

        lblArSlutdatum.setText("ÅÅÅÅ");

        lblManadSlutdatum.setText("MM");

        lblDagSlutdatum.setText("DD");

        btnUppdatera.setText("Uppdatera!");
        btnUppdatera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUppdateraActionPerformed(evt);
            }
        });

        lblStatus.setText("Status:");

        btnStang.setText("Stäng");
        btnStang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStangActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRubrik, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbKursnamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblNyttKursnamn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfNyttKursnamn, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lblAngeDenNyaInfo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblRubrikValjKursen, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNyttStartdatum)
                            .addComponent(NyttSlutdatum)
                            .addComponent(cmbAmnen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(tfArStartdatum, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(108, 108, 108))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(tfManadSlutdatum, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tfManadStartdatum, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(39, 39, 39)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDagStartdatum)
                                    .addComponent(tfDagStartdatum, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(tfArSlutdatum, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblArSlutdatum)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblManadSlutdatum))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(lblArStartdatum)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblManadStartdatum))
                                    .addComponent(lblNyAmnesTillhorighet, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(50, 50, 50)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDagSlutdatum)
                                    .addComponent(tfDagSlutdatum, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(btnUppdatera)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lblStatus)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(lblStatusSvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(46, 46, 46)
                                        .addComponent(btnStang))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNyttFornamn)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(tfLararensFornamn)
                                        .addComponent(lblNyKurslarare, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(51, 51, 51)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNyttEfternamn)
                                    .addComponent(tfLararensEfternamn, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(51, 51, 51))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblRubrik, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblRubrikValjKursen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbKursnamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(lblAngeDenNyaInfo)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNyttKursnamn)
                    .addComponent(tfNyttKursnamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblNyttStartdatum)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblArStartdatum)
                    .addComponent(lblManadStartdatum)
                    .addComponent(lblDagStartdatum))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfArStartdatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfManadStartdatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfDagStartdatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NyttSlutdatum)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblArSlutdatum)
                    .addComponent(lblManadSlutdatum)
                    .addComponent(lblDagSlutdatum)
                    .addComponent(btnUppdatera))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfArSlutdatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfManadSlutdatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfDagSlutdatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblStatus)
                    .addComponent(lblStatusSvar, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNyKurslarare)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNyttFornamn)
                    .addComponent(lblNyttEfternamn))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfLararensFornamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfLararensEfternamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblNyAmnesTillhorighet)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmbAmnen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnStang)
                        .addGap(22, 22, 22))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated

        if (cmbAmnen.getItemCount() == 0) {
            dataHanterare.laggTillAmne(cmbAmnen);
        }
        if (cmbKursnamn.getItemCount() == 0) {
            dataHanterare.laggTillKursnamn(cmbKursnamn);
        }
    }//GEN-LAST:event_formWindowActivated

    private void btnUppdateraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUppdateraActionPerformed

        if (Validering.FaltArTom(tfNyttKursnamn) || Validering.FaltArTom(tfArStartdatum) || Validering.FaltArTom(tfManadStartdatum) || Validering.FaltArTom(tfDagStartdatum) || Validering.FaltArTom(tfArSlutdatum) || Validering.FaltArTom(tfManadSlutdatum) || Validering.FaltArTom(tfDagSlutdatum) || Validering.FaltArTom(tfLararensFornamn) || Validering.FaltArTom(tfLararensEfternamn)) {

            System.out.println("Ett eller flera textfält är tomma.");
            lblStatusSvar.setText("Uppdateringen lyckades ej!");
        } else if (!Validering.arHeltal(tfArStartdatum) || !Validering.arHeltal(tfManadStartdatum) || !Validering.arHeltal(tfDagStartdatum) || !Validering.arHeltal(tfArSlutdatum) || !Validering.arHeltal(tfManadSlutdatum) || !Validering.arHeltal(tfDagSlutdatum)) {
            System.out.println("Datumfälten innehåller text!");
            lblStatusSvar.setText("Uppdateringen lyckades ej!");
        } else if (!Validering.giltigDag(tfDagStartdatum) || !Validering.giltigDag(tfDagSlutdatum) || !Validering.giltigManad(tfManadStartdatum) || !Validering.giltigManad(tfManadSlutdatum)) {
            System.out.println("Angiven dag eller datum är overkliga!");
            lblStatusSvar.setText("Uppdateringen lyckades ej!");
        } else if (Validering.datumOrdning(tfArStartdatum, tfManadStartdatum, tfDagStartdatum, tfArSlutdatum, tfManadSlutdatum, tfDagSlutdatum)) {

            String kursnamn = cmbKursnamn.getSelectedItem().toString();
            String nyttKursnamn = tfNyttKursnamn.getText();
            String nyaKursensNamn = dataHanterare.namnFormat(nyttKursnamn);
            String nyttStartdatum = tfArStartdatum.getText() + "-" + tfManadStartdatum.getText() + "-" + tfDagStartdatum.getText();
            String nyttSlutdatum = tfArSlutdatum.getText() + "-" + tfManadSlutdatum.getText() + "-" + tfDagSlutdatum.getText();
            String lararFornamn = tfLararensFornamn.getText();
            String nyttLararFornamn = dataHanterare.namnFormat(lararFornamn);
            String lararEfternamn = tfLararensEfternamn.getText();
            String nyttLararEfternamn = dataHanterare.efternamnFormat(lararEfternamn);
            String amnesnamn = cmbAmnen.getSelectedItem().toString();
            int lararId = dataHanterare.getLararID(nyttLararFornamn, nyttLararEfternamn);
            int kursId = dataHanterare.getKursId(kursnamn);
            int amnesId = dataHanterare.getAmneId(amnesnamn);
            if (lararId != 0) {
                dataHanterare.andraKursInfo(kursId, nyaKursensNamn, nyttStartdatum, nyttSlutdatum, lararId, amnesId);
                lblStatusSvar.setText("Uppdateringen lyckades!");
            } else {
                lblStatusSvar.setText("Uppdateringen lyckades ej!");
            }

        }
    }//GEN-LAST:event_btnUppdateraActionPerformed

    private void btnStangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStangActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnStangActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NyttSlutdatum;
    private javax.swing.JButton btnStang;
    private javax.swing.JButton btnUppdatera;
    private javax.swing.JComboBox<String> cmbAmnen;
    private javax.swing.JComboBox<String> cmbKursnamn;
    private javax.swing.JLabel lblAngeDenNyaInfo;
    private javax.swing.JLabel lblArSlutdatum;
    private javax.swing.JLabel lblArStartdatum;
    private javax.swing.JLabel lblDagSlutdatum;
    private javax.swing.JLabel lblDagStartdatum;
    private javax.swing.JLabel lblManadSlutdatum;
    private javax.swing.JLabel lblManadStartdatum;
    private javax.swing.JLabel lblNyAmnesTillhorighet;
    private javax.swing.JLabel lblNyKurslarare;
    private javax.swing.JLabel lblNyttEfternamn;
    private javax.swing.JLabel lblNyttFornamn;
    private javax.swing.JLabel lblNyttKursnamn;
    private javax.swing.JLabel lblNyttStartdatum;
    private javax.swing.JLabel lblRubrik;
    private javax.swing.JLabel lblRubrikValjKursen;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblStatusSvar;
    private javax.swing.JTextField tfArSlutdatum;
    private javax.swing.JTextField tfArStartdatum;
    private javax.swing.JTextField tfDagSlutdatum;
    private javax.swing.JTextField tfDagStartdatum;
    private javax.swing.JTextField tfLararensEfternamn;
    private javax.swing.JTextField tfLararensFornamn;
    private javax.swing.JTextField tfManadSlutdatum;
    private javax.swing.JTextField tfManadStartdatum;
    private javax.swing.JTextField tfNyttKursnamn;
    // End of variables declaration//GEN-END:variables
}
