/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hogwarts;

/**
 *
 * @authors Gabriel Björk & Murhaf Jammal
 */
public class ElevMeny extends javax.swing.JFrame {

    /**
     * Creates new form ElevMeny
     */
    public ElevMeny() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        btnVisaEleverIElevhem = new javax.swing.JButton();
        btnVisaKurserForEnLarare = new javax.swing.JButton();
        btnVisaKurserFoEnElev = new javax.swing.JButton();
        btnVisaKursbetygForEnElev = new javax.swing.JButton();
        btnVisaElevhemsPoang = new javax.swing.JButton();
        btnVisaPrefektForEttElevhem = new javax.swing.JButton();
        btnStang = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Vad vill du göra idag?");
        jLabel1.setInheritsPopupMenu(false);

        btnVisaEleverIElevhem.setText("Se alla elever i ett elevhem");
        btnVisaEleverIElevhem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisaEleverIElevhemActionPerformed(evt);
            }
        });

        btnVisaKurserForEnLarare.setText("Se alla kurser för en lärare mellan två datum");
        btnVisaKurserForEnLarare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisaKurserForEnLarareActionPerformed(evt);
            }
        });

        btnVisaKurserFoEnElev.setText("Visa kurser för en elev");
        btnVisaKurserFoEnElev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisaKurserFoEnElevActionPerformed(evt);
            }
        });

        btnVisaKursbetygForEnElev.setText("Visa kursbetyg för en elev");
        btnVisaKursbetygForEnElev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisaKursbetygForEnElevActionPerformed(evt);
            }
        });

        btnVisaElevhemsPoang.setText("Visa information om elevhemspokalen");
        btnVisaElevhemsPoang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisaElevhemsPoangActionPerformed(evt);
            }
        });

        btnVisaPrefektForEttElevhem.setText("Visa prefekt för ett elevhem");
        btnVisaPrefektForEttElevhem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisaPrefektForEttElevhemActionPerformed(evt);
            }
        });

        btnStang.setText("Stäng");
        btnStang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStangActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnVisaElevhemsPoang, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                            .addComponent(btnVisaEleverIElevhem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnVisaKurserFoEnElev, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnVisaKurserForEnLarare, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnVisaKursbetygForEnElev, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnVisaPrefektForEttElevhem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnStang)
                .addGap(58, 58, 58))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnVisaEleverIElevhem, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(btnVisaKurserForEnLarare, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVisaKurserFoEnElev, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVisaKursbetygForEnElev, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnVisaPrefektForEttElevhem, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(btnVisaElevhemsPoang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 131, Short.MAX_VALUE)
                .addComponent(btnStang)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void btnVisaKurserForEnLarareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisaKurserForEnLarareActionPerformed
        //Skapar och startar en ny SeKurserForEnLarareMellanDatum
        new SeKurserForEnLarareMellanDatum().setVisible(true);
    }//GEN-LAST:event_btnVisaKurserForEnLarareActionPerformed

    private void btnVisaKurserFoEnElevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisaKurserFoEnElevActionPerformed
        //Skapar och startar en ny VisaKurserForEnElev
        new VisaKurserForEnElev().setVisible(true);

    }//GEN-LAST:event_btnVisaKurserFoEnElevActionPerformed

    private void btnVisaEleverIElevhemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisaEleverIElevhemActionPerformed
        //Skapar och startar en ny KollaEleverIEttElevhem
        new KollaEleverIEttElevhem().setVisible(true);
    }//GEN-LAST:event_btnVisaEleverIElevhemActionPerformed

    private void btnVisaElevhemsPoangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisaElevhemsPoangActionPerformed
        //Skapar och startar en ny Elevhemspokal
        new Elevhemspokal().setVisible(true);
    }//GEN-LAST:event_btnVisaElevhemsPoangActionPerformed

    private void btnVisaKursbetygForEnElevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisaKursbetygForEnElevActionPerformed
        //Skapar och startar en ny KursbetygForEnElev
        new KursbetygForEnElev().setVisible(true);
    }//GEN-LAST:event_btnVisaKursbetygForEnElevActionPerformed

    private void btnVisaPrefektForEttElevhemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisaPrefektForEttElevhemActionPerformed
        //Skapar och startar en ny PrefektForEttElevhem
        new PrefektForEttElevhem().setVisible(true);
    }//GEN-LAST:event_btnVisaPrefektForEttElevhemActionPerformed

    private void btnStangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStangActionPerformed
        //Stänger ner befentlig JFrame
        this.dispose();
    }//GEN-LAST:event_btnStangActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnStang;
    private javax.swing.JButton btnVisaEleverIElevhem;
    private javax.swing.JButton btnVisaElevhemsPoang;
    private javax.swing.JButton btnVisaKursbetygForEnElev;
    private javax.swing.JButton btnVisaKurserFoEnElev;
    private javax.swing.JButton btnVisaKurserForEnLarare;
    private javax.swing.JButton btnVisaPrefektForEttElevhem;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
