/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hogwarts;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import oru.inf.InfDB;

/**
 *
 * @authors Gabriel Björk & Murhaf Jammal
 */
public class KursbetygForEnElev extends javax.swing.JFrame {

    private DataHanterare dataHanterare;
    private InfDB databasen;

    /**
     * Creates new form KursbetygForEnElev
     */
    public KursbetygForEnElev() {
        databasen = DataHanterare.dataHanterare();
        dataHanterare = new DataHanterare();
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        lblVisaKursbetygForEnElev = new javax.swing.JLabel();
        lblVanligenAngeForOchEfternamn = new javax.swing.JLabel();
        txtFornamn = new javax.swing.JTextField();
        lblFornamn = new javax.swing.JLabel();
        lblEfternamn = new javax.swing.JLabel();
        txtEfternamn = new javax.swing.JTextField();
        btnVisaBetyg = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtKurs = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtBetyg = new javax.swing.JTextArea();
        lblKursnamn = new javax.swing.JLabel();
        lblBetyg = new javax.swing.JLabel();
        btnClose = new javax.swing.JButton();
        lblFel = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblVisaKursbetygForEnElev.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblVisaKursbetygForEnElev.setText("Visa kursbetyg för en elev");

        lblVanligenAngeForOchEfternamn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblVanligenAngeForOchEfternamn.setText("Vänligen ange för- och efternamnet på eleven");

        txtFornamn.setMinimumSize(new java.awt.Dimension(4, 4));

        lblFornamn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblFornamn.setText("Förnamn:");

        lblEfternamn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblEfternamn.setText("Efternamn:");

        btnVisaBetyg.setText("Visa kursbetyg");
        btnVisaBetyg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisaBetygActionPerformed(evt);
            }
        });

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        txtKurs.setEditable(false);
        txtKurs.setColumns(20);
        txtKurs.setRows(5);
        jScrollPane2.setViewportView(txtKurs);

        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        txtBetyg.setEditable(false);
        txtBetyg.setColumns(20);
        txtBetyg.setRows(5);
        jScrollPane3.setViewportView(txtBetyg);

        lblKursnamn.setText("Kurs");

        lblBetyg.setText("Betyg");

        btnClose.setText("Stäng");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        lblFel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblFel.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblVanligenAngeForOchEfternamn)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(59, 59, 59)
                            .addComponent(btnVisaBetyg)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(lblFel, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(8, 8, 8)
                                    .addComponent(lblFornamn, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(txtFornamn, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(39, 39, 39)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtEfternamn, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblEfternamn, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(lblVisaKursbetygForEnElev, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblKursnamn)
                        .addGap(82, 82, 82)
                        .addComponent(lblBetyg)
                        .addGap(69, 69, 69))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnClose)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblKursnamn)
                            .addComponent(lblBetyg)))
                    .addComponent(lblVisaKursbetygForEnElev, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblVanligenAngeForOchEfternamn)
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFornamn, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEfternamn, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFornamn, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEfternamn))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnVisaBetyg, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnClose)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * hämtar, listar och skriver ut kurser för en elev.
     *
     * @param elevId
     */
    public void listaKurser(int elevId) {
        ArrayList<String> kurser = dataHanterare.visaKursbetygKursnamn(elevId);
        int i = 0;
        String skrivut = "";
        while (i < kurser.size()) {
            skrivut += " " + kurser.get(i) + "\n";
            i++;
        }
        txtKurs.setText(skrivut);
    }

    /**
     * hämtar, listar och skriver ut betyg för en elev.
     *
     * @param elevId
     */
    public void listaBetyg(int elevId) {
        ArrayList<String> betyg = dataHanterare.visaBetygbeskrivning(elevId);
        int i = 0;
        String skrivut = "";
        while (i < betyg.size()) {
            skrivut += " " + betyg.get(i) + "\n";
            i++;
        }
        txtBetyg.setText(skrivut);
    }

    /**
     * textfält valideras. elevens idn hämtas. om eleven finns listas kurser &
     * betyg för eleven. vid fel skickas meddelande.
     *
     * @param evt
     */
    private void btnVisaBetygActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisaBetygActionPerformed
        if (!Validering.FaltArTom(txtFornamn)) {
            if (!Validering.FaltArTom(txtEfternamn)) {
                txtKurs.setText(null);
                txtBetyg.setText(null);
                String fornamn=txtFornamn.getText();
                String elevensFornamn= dataHanterare.namnFormat(fornamn);
                String efternamn=txtEfternamn.getText();
                String elevensEfternamn= dataHanterare.efternamnFormat(efternamn);
                int elevId = dataHanterare.getElevId(elevensFornamn, elevensEfternamn);
                if (elevId != 0) {
                    try {
                        listaKurser(elevId);
                        listaBetyg(elevId);
                    } catch (NullPointerException e) {
                        System.out.println("Felmeddelande: " + e);
                        JOptionPane.showMessageDialog(null, "Eleven " + txtFornamn.getText() + " " + txtEfternamn.getText() + " har inga registrerade betyg i någon kurs.");
                    }
                }
            }
        }
    }//GEN-LAST:event_btnVisaBetygActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnVisaBetyg;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblBetyg;
    private javax.swing.JLabel lblEfternamn;
    private javax.swing.JLabel lblFel;
    private javax.swing.JLabel lblFornamn;
    private javax.swing.JLabel lblKursnamn;
    private javax.swing.JLabel lblVanligenAngeForOchEfternamn;
    private javax.swing.JLabel lblVisaKursbetygForEnElev;
    private javax.swing.JTextArea txtBetyg;
    private javax.swing.JTextField txtEfternamn;
    private javax.swing.JTextField txtFornamn;
    private javax.swing.JTextArea txtKurs;
    // End of variables declaration//GEN-END:variables
}
