/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hogwarts;

import javax.swing.JOptionPane;
import oru.inf.InfDB;

/**
 *
 * @authors Gabriel Björk & Murhaf Jammal
 */
public class LarareInloggning extends javax.swing.JFrame {

    private DataHanterare dataHanterare;
    private InfDB databasen;

    /**
     * Creates new form LarareInloggning
     */
    public LarareInloggning() {
        dataHanterare = new DataHanterare();
        databasen = DataHanterare.dataHanterare();
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfInloggningsMeny = new javax.swing.JLabel();
        tfLarareFornamn = new javax.swing.JTextField();
        tfLarareEfternamn = new javax.swing.JTextField();
        lfLarareLosenord = new javax.swing.JPasswordField();
        lblLarareFornamn = new javax.swing.JLabel();
        lblLosenord = new javax.swing.JLabel();
        btnLoggaIn = new javax.swing.JButton();
        lblLarareEfternamn = new javax.swing.JLabel();
        btnRensa = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tfInloggningsMeny.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tfInloggningsMeny.setText("Inloggnings Meny");

        lblLarareFornamn.setText("Förnamn:");

        lblLosenord.setText("Lösenord:");

        btnLoggaIn.setText("Logga in");
        btnLoggaIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoggaInActionPerformed(evt);
            }
        });

        lblLarareEfternamn.setText("Efternamn:");

        btnRensa.setText("Rensa");
        btnRensa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRensaActionPerformed(evt);
            }
        });

        btnClose.setText("Stäng");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tfInloggningsMeny, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblLarareFornamn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfLarareFornamn, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)))
                .addGap(7, 7, 7)
                .addComponent(lblLarareEfternamn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfLarareEfternamn, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 120, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnClose))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(203, 203, 203)
                                .addComponent(btnLoggaIn)
                                .addGap(62, 62, 62)
                                .addComponent(btnRensa))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(124, 124, 124)
                                .addComponent(lblLosenord)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lfLarareLosenord, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tfInloggningsMeny, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfLarareFornamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfLarareEfternamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLarareFornamn)
                    .addComponent(lblLarareEfternamn))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lfLarareLosenord, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLosenord))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLoggaIn)
                    .addComponent(btnRensa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 121, Short.MAX_VALUE)
                .addComponent(btnClose)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * textfält valideras. lärares idn hämtas. lärares lösenord hämtas och
     * jämförs mot lösenordsfältet. administratörstatus kontrolleras. status/fel
     * meddelande skrivs ut beroende på tomma textfält, felaktig information
     * eller lyckad inloggning
     *
     * @param evt
     */
    private void btnLoggaInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoggaInActionPerformed
        if (Validering.FaltArTom(tfLarareFornamn) || Validering.FaltArTom(tfLarareEfternamn)) {
          System.out.println("Valideringen fält är tom är true");
        } else if (Validering.pwFaltArTom(lfLarareLosenord)) {
            System.out.println("Losenordet finnse ej");
        } else {
            String fornamn = tfLarareFornamn.getText();
            String lararensFornamn = dataHanterare.namnFormat(fornamn);
            String efternamn = tfLarareEfternamn.getText();
            String lararensEfternamn = dataHanterare.efternamnFormat(efternamn);
            char[] larareLosenord = lfLarareLosenord.getPassword();

            int lararId = dataHanterare.getLararID(lararensFornamn, lararensEfternamn);
            if (lararId != 0) {
                if (DataHanterare.kollaInloggning(lararId, larareLosenord)) {
                    if (dataHanterare.hamtaAdministratorInfo(lararId)) {
                        JOptionPane.showMessageDialog(null, "Du är nu inloggad som administratör!");
                        tomFalten();
                        new AdministratorMeny(lararId).setVisible(true);
                        this.dispose();
                    } else {
                        JOptionPane.showMessageDialog(null, "Du är nu inloggad som lärare!");
                        tomFalten();
                        new LarareMeny(lararId).setVisible(true);
                        this.dispose();

                    }
                } else if (!DataHanterare.kollaInloggning(lararId, larareLosenord)) {
                    JOptionPane.showMessageDialog(null, "Inloggningen lyckades ej! Vänligen försök igen!");
                }
            }
        }


    }//GEN-LAST:event_btnLoggaInActionPerformed

    private void btnRensaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRensaActionPerformed
        // En knapp för att rensa alla textfält i inloggningssidan.
        tomFalten();
    }//GEN-LAST:event_btnRensaActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    /**
     * en metod som tömmer alla textfälten i inloggningssidan
     */
    public void tomFalten() {
        tfLarareFornamn.setText(null);
        tfLarareEfternamn.setText(null);
        lfLarareLosenord.setText(null);
        tfLarareFornamn.requestFocus();
    }
    ;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnLoggaIn;
    private javax.swing.JButton btnRensa;
    private javax.swing.JLabel lblLarareEfternamn;
    private javax.swing.JLabel lblLarareFornamn;
    private javax.swing.JLabel lblLosenord;
    private javax.swing.JPasswordField lfLarareLosenord;
    private javax.swing.JLabel tfInloggningsMeny;
    private javax.swing.JTextField tfLarareEfternamn;
    private javax.swing.JTextField tfLarareFornamn;
    // End of variables declaration//GEN-END:variables
}
