/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hogwarts;

import javax.swing.JOptionPane;
import oru.inf.InfDB;

/**
 *
 * @authors Gabriel Björk & Murhaf Jammal
 */
public class RegistreraNyElev extends javax.swing.JFrame {

    private DataHanterare dataHanterare;
    private InfDB databasen;
    //new RegistreraNyElev().setVisible(true);

    /**
     * Creates new form RegistreraNyElev
     *
     * @param id
     */
    public RegistreraNyElev() {
        databasen = DataHanterare.dataHanterare();
        dataHanterare = new DataHanterare();
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnregistreraElev = new javax.swing.JButton();
        txtFornamn = new javax.swing.JTextField();
        txtEfternamn = new javax.swing.JTextField();
        lblFornamn = new javax.swing.JLabel();
        lblEfternamn = new javax.swing.JLabel();
        lblSovsal = new javax.swing.JLabel();
        lblTitel = new javax.swing.JLabel();
        btnClose = new javax.swing.JButton();
        lblLyckad = new javax.swing.JLabel();
        lblElevhem = new javax.swing.JLabel();
        cboxElevhem = new javax.swing.JComboBox<>();
        cboxSovsal = new javax.swing.JComboBox<>();
        lblVaning = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        btnregistreraElev.setText("Registrera elev");
        btnregistreraElev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregistreraElevActionPerformed(evt);
            }
        });

        lblFornamn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblFornamn.setText("Förnamn:");

        lblEfternamn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblEfternamn.setText("Efternamn:");

        lblSovsal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblSovsal.setText("Sovsal:");

        lblTitel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTitel.setText("Registrera ny elev");

        btnClose.setText("Stäng");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        lblElevhem.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblElevhem.setText("Elevhem:");

        cboxElevhem.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        cboxSovsal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cboxSovsal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));

        lblVaning.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblVaning.setText("Våning");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cboxElevhem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblVaning)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cboxSovsal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnClose)
                            .addComponent(lblElevhem)
                            .addComponent(lblLyckad)
                            .addComponent(lblTitel)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblFornamn)
                                    .addComponent(txtFornamn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblEfternamn)
                                    .addComponent(txtEfternamn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblSovsal)))
                            .addComponent(btnregistreraElev))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(0, 67, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblTitel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEfternamn)
                    .addComponent(lblFornamn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFornamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEfternamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblElevhem)
                    .addComponent(lblSovsal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboxElevhem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboxSovsal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblVaning))
                .addGap(18, 18, 18)
                .addComponent(btnregistreraElev)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLyckad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(btnClose)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * textfält valideras. idn för elevhem hämtas. idn för sovsal hämtas. elev
     * registreras och status meddelande skrivs ut.
     *
     * @param evt
     */
    private void btnregistreraElevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregistreraElevActionPerformed
        if (!Validering.FaltArTom(txtFornamn)) {
            if (!Validering.FaltArTom(txtEfternamn)) {
                String fornamn = dataHanterare.namnFormat(txtFornamn.getText());
                String efternamn = dataHanterare.efternamnFormat(txtEfternamn.getText());
                int elevhemId = dataHanterare.getElevhemId(cboxElevhem);
                int sovsalId = dataHanterare.getSovsalId(elevhemId, cboxSovsal);
                if (dataHanterare.registreraNyElev(fornamn, efternamn, sovsalId)) {
                    lblLyckad.setText(fornamn + " " + efternamn + " är nu registrerad!");
                } else {
                    lblLyckad.setText("Registreringen lyckades ej!");
                }

            }
        }
    }//GEN-LAST:event_btnregistreraElevActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    /**
     * elevhemmen läggs till i comboboxen från db
     *
     * @param evt
     */
    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        if (cboxElevhem.getItemCount() == 0) {
            dataHanterare.laggTillElevhem(cboxElevhem);
        }
    }//GEN-LAST:event_formWindowActivated

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnregistreraElev;
    private javax.swing.JComboBox<String> cboxElevhem;
    private javax.swing.JComboBox<String> cboxSovsal;
    private javax.swing.JLabel lblEfternamn;
    private javax.swing.JLabel lblElevhem;
    private javax.swing.JLabel lblFornamn;
    private javax.swing.JLabel lblLyckad;
    private javax.swing.JLabel lblSovsal;
    private javax.swing.JLabel lblTitel;
    private javax.swing.JLabel lblVaning;
    private javax.swing.JTextField txtEfternamn;
    private javax.swing.JTextField txtFornamn;
    // End of variables declaration//GEN-END:variables
}
