/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hogwarts;

import javax.swing.JOptionPane;
import oru.inf.InfDB;

/**
 *
 * @authors Gabriel Björk & Murhaf Jammal
 */
public class RegistreraKursbetygForEnElev extends javax.swing.JFrame {

    private InfDB databasen;
    private DataHanterare dataHanterare;

    /**
     * Creates new form RegistereraKursbetygForEnElev
     */
    public RegistreraKursbetygForEnElev() {
        databasen = DataHanterare.dataHanterare();
        dataHanterare = new DataHanterare();
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblRubrikRegistreraEttNyttBetyg = new javax.swing.JLabel();
        tfElevensFornamn = new javax.swing.JTextField();
        tfElevensEfternamn = new javax.swing.JTextField();
        lblElevensFornamn = new javax.swing.JLabel();
        lblElevensEfternamn = new javax.swing.JLabel();
        lblKursNamn = new javax.swing.JLabel();
        lblBetyg = new javax.swing.JLabel();
        btnRegistrera = new javax.swing.JButton();
        cmbValjKurs = new javax.swing.JComboBox<>();
        cmbValjBetyg = new javax.swing.JComboBox<>();
        btnStang = new javax.swing.JButton();
        lblLyckad = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        lblRubrikRegistreraEttNyttBetyg.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblRubrikRegistreraEttNyttBetyg.setText("Registrera ett nytt kursbetyg för en elev");

        lblElevensFornamn.setText("Elevens Förnamn:");

        lblElevensEfternamn.setText("Elevens Efternamn:");

        lblKursNamn.setText("Kursnamn:");

        lblBetyg.setText("Betyg:");

        btnRegistrera.setText("Registrera!");
        btnRegistrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistreraActionPerformed(evt);
            }
        });

        btnStang.setText("Stäng");
        btnStang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStangActionPerformed(evt);
            }
        });

        lblLyckad.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblRubrikRegistreraEttNyttBetyg, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 60, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblKursNamn, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBetyg, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbValjKurs, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbValjBetyg, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblElevensEfternamn, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfElevensEfternamn, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                    .addComponent(lblElevensFornamn)
                    .addComponent(tfElevensFornamn))
                .addGap(77, 77, 77))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(btnStang))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnRegistrera, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                            .addComponent(lblLyckad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(117, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblRubrikRegistreraEttNyttBetyg, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblElevensFornamn)
                    .addComponent(lblKursNamn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfElevensFornamn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbValjKurs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblElevensEfternamn)
                    .addComponent(lblBetyg))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfElevensEfternamn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbValjBetyg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnRegistrera, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblLyckad, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnStang)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * textfält valideras. kurs registreras. statusmeddelande skrivs ut.
     *
     * @param evt
     */
    private void btnRegistreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistreraActionPerformed
        lblLyckad.setText("");
        if (!Validering.FaltArTomUtanPopUp(tfElevensFornamn) && !Validering.FaltArTomUtanPopUp(tfElevensEfternamn)) {
            String fornamn = dataHanterare.namnFormat(tfElevensFornamn.getText());
            String efternamn = dataHanterare.efternamnFormat(tfElevensEfternamn.getText());
            String kursnamn = cmbValjKurs.getSelectedItem().toString();
            String betyg = cmbValjBetyg.getSelectedItem().toString();
            if (dataHanterare.registreraNyttBetygForEnElev(kursnamn, betyg, fornamn, efternamn)) {
                lblLyckad.setText("Betyget har registrerats");
            } else {
                lblLyckad.setText("Registreringen lyckades ej");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Vänligen fyll i alla textfälten ovan!");
        }
    }//GEN-LAST:event_btnRegistreraActionPerformed

    private void btnStangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStangActionPerformed

        this.dispose();
    }//GEN-LAST:event_btnStangActionPerformed

    /**
     * kurslista och betyglista hämtas och läggs till i combobox från db
     *
     * @param evt
     */
    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated

        if (cmbValjKurs.getItemCount() == 0) {
            dataHanterare.laggTillKursnamn(cmbValjKurs);
        }
        if (cmbValjBetyg.getItemCount() == 0) {
            dataHanterare.laggTillBetygsBeteckning(cmbValjBetyg);
        }
    }//GEN-LAST:event_formWindowActivated


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrera;
    private javax.swing.JButton btnStang;
    private javax.swing.JComboBox<String> cmbValjBetyg;
    private javax.swing.JComboBox<String> cmbValjKurs;
    private javax.swing.JLabel lblBetyg;
    private javax.swing.JLabel lblElevensEfternamn;
    private javax.swing.JLabel lblElevensFornamn;
    private javax.swing.JLabel lblKursNamn;
    private javax.swing.JLabel lblLyckad;
    private javax.swing.JLabel lblRubrikRegistreraEttNyttBetyg;
    private javax.swing.JTextField tfElevensEfternamn;
    private javax.swing.JTextField tfElevensFornamn;
    // End of variables declaration//GEN-END:variables
}
