/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hogwarts;

import javax.swing.JOptionPane;
import oru.inf.InfDB;

/**
 *
 * @authors Gabriel Björk & Murhaf Jammal
 */
public class RegistreraNyKurs extends javax.swing.JFrame {

    private DataHanterare dataHanterare;
    private InfDB databasen;

    /**
     * Creates new form RegistreraNyKurs
     */
    public RegistreraNyKurs() {
        databasen = DataHanterare.dataHanterare();
        dataHanterare = new DataHanterare();
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitel = new javax.swing.JLabel();
        lblNamn = new javax.swing.JLabel();
        lblAmne = new javax.swing.JLabel();
        lblLarare = new javax.swing.JLabel();
        lblStart = new javax.swing.JLabel();
        lblSlut = new javax.swing.JLabel();
        cboxAmne = new javax.swing.JComboBox<>();
        txtKurs = new javax.swing.JTextField();
        txtStartyear = new javax.swing.JTextField();
        txtSlutyear = new javax.swing.JTextField();
        cboxLarare = new javax.swing.JComboBox<>();
        btnGo = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        lblLyckad = new javax.swing.JLabel();
        txtStartmonth = new javax.swing.JTextField();
        txtStartday = new javax.swing.JTextField();
        txtSlutmonth = new javax.swing.JTextField();
        txtSlutday = new javax.swing.JTextField();
        lblArStartdatum = new javax.swing.JLabel();
        lblManadStartdatum = new javax.swing.JLabel();
        lblDagStartdatum = new javax.swing.JLabel();
        lblArSlutdatum = new javax.swing.JLabel();
        lblManadSlutdatum = new javax.swing.JLabel();
        lblDagSlutdatum = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        lblTitel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTitel.setText("Registrera ny kurs");

        lblNamn.setText("Kursnamn:");

        lblAmne.setText("Ämnestillhörighet:");

        lblLarare.setText("Lärare:");

        lblStart.setText("Startdatum:");

        lblSlut.setText("Slutdatum:");

        btnGo.setText("Registrera");
        btnGo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoActionPerformed(evt);
            }
        });

        btnClose.setText("Stäng");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        lblLyckad.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N

        txtSlutmonth.setPreferredSize(new java.awt.Dimension(24, 20));

        txtSlutday.setPreferredSize(new java.awt.Dimension(24, 20));

        lblArStartdatum.setText("ÅÅÅÅ");

        lblManadStartdatum.setText("MM");

        lblDagStartdatum.setText("DD");

        lblArSlutdatum.setText("ÅÅÅÅ");

        lblManadSlutdatum.setText("MM");

        lblDagSlutdatum.setText("DD");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnGo)
                                    .addComponent(lblLyckad, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cboxLarare, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblLarare)
                                    .addComponent(lblStart))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cboxAmne, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblAmne)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtSlutyear, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtSlutmonth, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtSlutday, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblArSlutdatum)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblManadSlutdatum)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblDagSlutdatum))
                                    .addComponent(lblSlut))))
                        .addGap(0, 3, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnClose))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblTitel, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txtStartyear, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtStartmonth, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lblNamn)
                                                .addComponent(txtKurs, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtStartday, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(lblArStartdatum)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblManadStartdatum)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblDagStartdatum)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(lblTitel)
                        .addGap(18, 18, 18)
                        .addComponent(lblNamn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtKurs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSlut)
                            .addComponent(lblStart))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblArSlutdatum)
                            .addComponent(lblDagStartdatum)
                            .addComponent(lblManadStartdatum)
                            .addComponent(lblArStartdatum)
                            .addComponent(lblManadSlutdatum)
                            .addComponent(lblDagSlutdatum))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtStartmonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtStartday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtSlutmonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtSlutday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtSlutyear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtStartyear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLarare)
                    .addComponent(lblAmne))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboxLarare, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboxAmne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnGo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLyckad, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClose))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * ämnen + lärare läggs till i combobox från db.
     *
     * @param evt
     */
    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        if (cboxAmne.getItemCount() == 0) {
            dataHanterare.laggTillAmne(cboxAmne);
        }
        if (cboxLarare.getItemCount() == 0) {
            dataHanterare.laggTillLarare(cboxLarare);
        }
        lblLyckad.setText("");
    }//GEN-LAST:event_formWindowActivated

    /**
     * textfält valideras. lokal variabler deklareras och tilldelas data som ska
     * registreras. kurs registreras och status meddelande skrivs ut.
     *
     * @param evt
     */
    private void btnGoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoActionPerformed
        lblLyckad.setText("");
        if (Validering.FaltArTom(txtKurs) || Validering.FaltArTom(txtStartyear) || Validering.FaltArTom(txtStartmonth)
                || Validering.FaltArTom(txtStartday) || Validering.FaltArTom(txtSlutyear) || Validering.FaltArTom(txtSlutmonth)
                || Validering.FaltArTom(txtSlutday)) {
            System.out.println("Valideringen av textfälten är false");
            lblLyckad.setText("Registreringen lyckades ej!");
        } else if (!Validering.arHeltal(txtStartyear) || !Validering.arHeltal(txtStartmonth) || !Validering.arHeltal(txtStartday)
                || !Validering.arHeltal(txtSlutyear) || !Validering.arHeltal(txtSlutmonth) || !Validering.arHeltal(txtSlutday)) {
            System.out.println("Datumfälten innehåller annat än siffror");
            lblLyckad.setText("Registreringen lyckades ej!");
        } else if (!Validering.giltigDag(txtSlutday) || !Validering.giltigDag(txtStartday) || !Validering.giltigManad(txtSlutmonth) || !Validering.giltigManad(txtStartmonth)) {
            System.out.println("Angiven dag eller månad är ogiltig");
            lblLyckad.setText("Registreringen lyckades ej!");
        } else if (Validering.datumOrdning(txtStartyear, txtStartmonth, txtStartday, txtSlutyear, txtSlutmonth, txtSlutday)) {
            int amneId = dataHanterare.getAmneId(cboxAmne.getSelectedItem().toString());
            int lararId = cboxLarare.getSelectedIndex() + 1;
            String startdatum = txtStartyear.getText() + "-" + txtStartmonth.getText() + "-" + txtStartday.getText();
            String slutdatum = txtSlutyear.getText() + "-" + txtSlutmonth.getText() + "-" + txtSlutday.getText();
            String kursnamn = dataHanterare.namnFormat(txtKurs.getText());
            if (dataHanterare.arUnikKurs(kursnamn)) {
                if (dataHanterare.registreraNyKurs(kursnamn, amneId, startdatum, slutdatum, lararId)) {
                    lblLyckad.setText("Kursen '" + kursnamn + "' är nu registrerad");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Det finns redan en kurs med namnet '" + kursnamn + "'.");
            }
        }
    }//GEN-LAST:event_btnGoActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnGo;
    private javax.swing.JComboBox<String> cboxAmne;
    private javax.swing.JComboBox<String> cboxLarare;
    private javax.swing.JLabel lblAmne;
    private javax.swing.JLabel lblArSlutdatum;
    private javax.swing.JLabel lblArStartdatum;
    private javax.swing.JLabel lblDagSlutdatum;
    private javax.swing.JLabel lblDagStartdatum;
    private javax.swing.JLabel lblLarare;
    private javax.swing.JLabel lblLyckad;
    private javax.swing.JLabel lblManadSlutdatum;
    private javax.swing.JLabel lblManadStartdatum;
    private javax.swing.JLabel lblNamn;
    private javax.swing.JLabel lblSlut;
    private javax.swing.JLabel lblStart;
    private javax.swing.JLabel lblTitel;
    private javax.swing.JTextField txtKurs;
    private javax.swing.JTextField txtSlutday;
    private javax.swing.JTextField txtSlutmonth;
    private javax.swing.JTextField txtSlutyear;
    private javax.swing.JTextField txtStartday;
    private javax.swing.JTextField txtStartmonth;
    private javax.swing.JTextField txtStartyear;
    // End of variables declaration//GEN-END:variables
}
